export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const OPEN_PROJECT = "OPEN_PROJECT";
export const CLOSE_PROJECT = "CLOSE_PROJECT";
