export const FETCH_PROJECTS_SUCCESS = "FETCH_PROJECTS_SUCCESS";
export const FETCH_PROJECTS_FAIL = "FETCH_PROJECTS_FAIL";
export const OPEN_PROJECT = "OPEN_PROJECT";
export const CLOSE_PROJECT = "CLOSE_PROJECT";

export const SET_MESSAGE = "SET_MESSAGE";
export const RESET_MESSAGE = "RESET_MESSAGE";

export const FETCH_SKILLS_START = "FETCH_SKILLS_START";
export const FETCH_SKILLS_SUCCESS = "FETCH_SKILLS_SUCCESS";
export const FETCH_SKILLS_FAIL = "FETCH_SKILLS_FAIL";
